### ISSUE TITLE
License and legal stuff

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [FemLol2003/Gacha-Club-Assets#2]
Heya, could you add a license to this repo stating what can and can't be done with the assets, and do you know if it's even legal to use in a commercial product? I want to create my own game but don't want to risk a lawsuit from Lunime haha

**Comment by TuxPenguin09** [comment]
Since the developer of Gacha Club didn't open their game's source code to public, The license is a proprietary to Lunime, not FemLol2003. It could be illegal since most of the files here has reverse engineered Gacha Club that anyone can modify.
If they only store those SVG files like the rig for arms, head, legs, etc. but not all of the ActionScript files.
